### ISSUE TITLE
Ruby script

### ISSUE THREAD

**Issue by VergilYotov** [antirez/smaz#7]
Hello, can you release the ruby script to build new specialized dictionaries ?
Even if its for reference only. 
Thanks!

**Comment by antirez** [comment]
I lost it, sorry :-(

**Comment by antirez** [comment]
p.s. check the forks in this repository, there is a much improved version of Smaz with all the tools needed.

**Comment by VergilYotov** [comment]
Thanks, I will check them out !

**Comment by 5clai** [comment]
> Thanks, I will check them out !

Hi, did you found the script?
